### ISSUE TITLE
Publish unminified code

### ISSUE THREAD

**Issue by luqmaan** [misterfresh/mapbox-gl-js-animation-example#1]
I found this repo from https://github.com/mapbox/mapbox-gl-js/issues/2317.

I'd love to see your code, but the only checked in code is bundle.js.

**Comment by misterfresh** [comment]
I have to clean it up a bit, right now its full of hacks, shortcuts and global variables. Actually I was thinking of uploading a fork of mapbox-gl named "Mapbox Animation" or something similar, with a new source type AnimationSource, based on GeoJsonSource but with a new feature : in each feature properties you can set a new property "nextPosition" and your marker would transition smoothly to that position automagically.
I was waiting for some feedback on that from mourner of jfirebaugh before I invest any time in it. Possible that they are working on something like that as well. Other than that if you want to hack the mapbox source I think I described how to do it in the other thread.

**Comment by luqmaan** [comment]
>  fork of mapbox-gl named "Mapbox Animation" or something similar, with a new source type AnimationSource, based on GeoJsonSource but with a new feature : in each feature properties you can set a new property "nextPosition" and your marker would transition smoothly to that position automagically.

That would be amazing. It seems that the only way to animate markers (without forking) is with repeated calls to `setData`, which seems bad for performant animations.

I'm trying to make a public transit map that shows a hundred or so markers and animates them all at the same time every few seconds. Something like http://allthebuses.com.

**Comment by misterfresh** [comment]
I published the unminified code with an easy-to-use API in the following repo : 
[mapbox animation](https://github.com/misterfresh/mapbox-animation)

**Comment by luqmaan** [comment]
Thanks!

Unfortunately, the animations aren't smooth on my Macbook.

I decided to try out another approach: just make the animated markers regular DOM elements and animate them with css.

It seems to work pretty well even with 300+ markers: http://bl.ocks.org/luqmaan/9abba496e4d51cafb43c78ae21ab436b

**Comment by misterfresh** [comment]
Interesting approach.
http://stackoverflow.com/questions/30261999/webgl-performance-issues-with-retina-macbook-pro

I also noticed while demoing the traffic simulation towards prospects that the animation was choppy on his retina macbook pro. This is a shortcoming of the macbook pro though.

Performing the animation on the GPU should yield much better performance in most scenarios. At least that's what I'm noticing on a regular full HD screen connected to a macbook air. As far as I know browser CSS transitions are actually using the GPU under the hood.
